name: base
channels:
    - defaults
dependencies:
    - python==3.12.8
    - numpy
    - conda-forge::tesseract
    - fastapi
    - sqlmodel
    - python-dotenv
    - psycopg2
    - uvicorn
    - bcrypt
    - pyjwt
    - alembic
    - conda-forge::openai
    - conda-forge::pytesseract
    - pip:
          - tabulate
          - opencv-python
 
