name: base
channels:
    - defaults
dependencies:
    - python==3.12.8
    - numpy
    - fastapi
    - sqlmodel
    - python-dotenv
    - psycopg2
    - uvicorn
    - bcrypt
    - pyjwt
    - alembic
    - cryptography
    - pytz
    - conda-forge::openai
    - conda-forge::tesseract
    - conda-forge::pytesseract
    - conda-forge::httpx
    - conda-forge::h2
    - conda-forge::fastapi_utils
    - pip:
          - tabulate
          - opencv-python
          - ics
