"""username_update_cascade

Revision ID: 47078a5a51c2
Revises: 85af32eeb847
Create Date: 2025-01-08 10:43:48.735854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '47078a5a51c2'
down_revision: Union[str, None] = '85af32eeb847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shift_username_fkey', 'shift', type_='foreignkey')
    op.create_foreign_key(None, 'shift', 'user', ['username'], ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shift', type_='foreignkey')
    op.create_foreign_key('shift_username_fkey', 'shift', 'user', ['username'], ['username'], onupdate='CASCADE')
    # ### end Alembic commands ###
