"""usersettings_calendar_event_title

Revision ID: 6a0d2fba3414
Revises: 061394c8645c
Create Date: 2025-01-09 11:14:26.934438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6a0d2fba3414'
down_revision: Union[str, None] = '061394c8645c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersettings', sa.Column('calendar_event_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usersettings', 'calendar_event_title')
    # ### end Alembic commands ###
