"""usersettings_notification_new_schedule

Revision ID: 73b557779f36
Revises: 6a0d2fba3414
Create Date: 2025-01-09 15:40:32.008362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '73b557779f36'
down_revision: Union[str, None] = '6a0d2fba3414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersettings', sa.Column('notifications_new_schedule', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usersettings', 'notifications_new_schedule')
    # ### end Alembic commands ###
