"""usersettings

Revision ID: 9bec35db1571
Revises: 47078a5a51c2
Create Date: 2025-01-09 10:26:13.358439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9bec35db1571'
down_revision: Union[str, None] = '47078a5a51c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersettings',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wage', sa.Float(), nullable=False),
    sa.Column('notifications_work_reminder', sa.Boolean(), nullable=False),
    sa.Column('notifications_work_reminder_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usersettings')
    # ### end Alembic commands ###
