"""shift_canceled2

Revision ID: bfd7738a6d20
Revises: 238eb64392ea
Create Date: 2024-12-21 21:27:53.376356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfd7738a6d20'
down_revision: Union[str, None] = '238eb64392ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shift', 'canceled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shift', 'canceled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
