"""UserDevice_relation

Revision ID: dcdd23261ccf
Revises: 23f9ecc893dc
Create Date: 2025-01-05 23:23:42.070271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dcdd23261ccf'
down_revision: Union[str, None] = '23f9ecc893dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'userdevice', 'user', ['username'], ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userdevice', type_='foreignkey')
    # ### end Alembic commands ###
