"""usersettings_notification_new_schedule_notnull

Revision ID: ead3e248f172
Revises: 73b557779f36
Create Date: 2025-01-09 15:41:26.656240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ead3e248f172'
down_revision: Union[str, None] = '73b557779f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usersettings', 'notifications_new_schedule',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usersettings', 'notifications_new_schedule',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
